// Curated Dwarf Fortress entities per CP437 tile index (0-255).
// Entry: [category, name, colourIndex?, note?]
// Categories: creature, item, terrain, building, plant, ui
// Colour index follows the DF 16-colour palette (see PALETTE in index.html).
// The default ASCII glyph set is used; individual tilesets may remap glyphs.

window.DF_CATEGORIES = {
  creature: "Creatures",
  item: "Items",
  terrain: "Terrain",
  building: "Buildings & furniture",
  plant: "Plants",
  ui: "Interface & markers",
};

const C = (n, c, note) => ["creature", n, c, note];
const I = (n, c, note) => ["item", n, c, note];
const T = (n, c, note) => ["terrain", n, c, note];
const B = (n, c, note) => ["building", n, c, note];
const P = (n, c, note) => ["plant", n, c, note];
const U = (n, c, note) => ["ui", n, c, note];

window.DF_ENTITIES = {
  1:  [C("Dwarf", 15, "colour shows profession"), C("Human", 15), C("Elf", 15), I("Dwarven figure (portrait/engraving)", 7)],
  2:  [C("Dwarf (alternate glyph)", 15, "used by some tilesets"), U("Selected unit", 14)],
  3:  [I("Heart (body part)", 12), U("Heart marker (health)", 12)],
  4:  [I("Rough gem", 11), T("Gem-bearing cluster", 11)],
  5:  [P("Plump helmet", 13, "crop & wild mushroom"), P("Tower-cap / fungus tree", 6), P("Tree (broadleaf canopy)", 2)],
  6:  [P("Tree (conifer / pine)", 2), P("Tree (dead / bare)", 6), P("Tree (cave fungus)", 9)],
  7:  [I("Boulder / rock", 7), I("Coin", 14), U("Bullet / list item", 15)],
  8:  [I("Container (barrel, bucket, bin)", 6), U("Inverse bullet", 15)],
  9:  [I("Ring", 14), I("Crown", 14), I("Coin (silver, gold, copper)", 7)],
  10: [B("Cage", 7), B("Trap (stone-fall, cage trap)", 7), I("Inverted ring", 14)],
  11: [U("Male (unit sex)", 9), C("Male creature", 9)],
  12: [U("Female (unit sex)", 13), C("Female creature", 13)],
  13: [I("Musical instrument", 6), I("Crafted note / engraving", 11)],
  14: [I("Musical instruments (alt)", 6)],
  15: [I("Cut gem", 11), B("Statue", 7), B("Well", 9), T("Sun / daylight", 14)],
  16: [U("Right arrow / selection", 14), B("Conveyor east", 7)],
  17: [U("Left arrow / selection", 14), B("Conveyor west", 7)],
  18: [T("Up/down staircase", 14, "both directions")],
  19: [U("Exclamation (alert / forbidden)", 12)],
  20: [U("Paragraph / text marker", 7)],
  21: [U("Section marker", 7)],
  22: [I("Metal bar (alt)", 7), B("Bar / bolt", 7)],
  23: [U("Up/down scroll", 7)],
  24: [T("Up staircase", 14), I("Bolt / arrow (ammunition)", 6), U("Scroll up", 15)],
  25: [T("Down staircase", 14), U("Scroll down", 15)],
  26: [U("Right arrow (pointer)", 14), B("Conveyor / track east", 7)],
  27: [U("Left arrow (pointer)", 14), B("Conveyor / track west", 7)],
  28: [B("Track corner", 7)],
  29: [U("Left/right scroll", 7)],
  30: [T("Up ramp", 7), T("Hill / mound", 6), B("Mountain / peak (world map)", 8)],
  31: [T("Down ramp", 7), U("Scroll down (alt)", 15)],
  32: [T("Open space / air", 0), T("Unexplored tile", 0), T("Empty floor", 0)],
  33: [I("Potion / flask", 13), U("Warning / alert", 12), T("Lava vent (rare)", 12)],
  34: [T("Grass (tall)", 10), P("Shrub", 2), I("Cloth / bolt", 15)],
  35: [B("Grate (floor or wall)", 7), B("Bridge", 6), T("Mineral cluster", 8), B("Rough wall (stone)", 8)],
  36: [I("Coins / money", 14), U("Currency marker", 14)],
  37: [I("Prepared meal", 6), I("Meat", 12), T("Ore vein (alt)", 7)],
  38: [U("Ampersand (text)", 15), C("Imp / demon (some tilesets)", 12)],
  39: [T("Pebbles / gravel", 8), T("Soil debris", 6), I("Rock / small stone", 7)],
  40: [U("Opening parenthesis (text)", 7), I("Weapon / blade (variant)", 7)],
  41: [U("Closing parenthesis (text)", 7), I("Weapon / blade (variant)", 7)],
  42: [T("Ore vein (unmined)", 14), T("Gem cluster", 11), T("Mined rubble / ore", 7)],
  43: [B("Door (variant)", 6), T("Cross-shaped wall (tileset-dependent)", 7)],
  44: [P("Shrub / sapling", 10), T("Dry grass / debris", 6), T("Small plant", 2)],
  45: [B("Hatch cover", 6), T("Minus / dash (text)", 7)],
  46: [T("Floor (stone, smoothed)", 8), T("Open ground / soil", 6), T("Sand", 14), T("Grass (short)", 2)],
  47: [I("Pick-axe / weapon (slash)", 7), B("Lever", 7), U("Slash (text)", 7)],
  48: [U("Digit 0 / counter", 15), I("Boulder (variant)", 7)],
  49: [U("Digit 1 / unit count", 15)],
  50: [U("Digit 2 / stacked units", 15)],
  51: [U("Digit 3 / stacked units", 15)],
  52: [U("Digit 4 / stacked units", 15)],
  53: [U("Digit 5 / stacked units", 15)],
  54: [U("Digit 6 / stacked units", 15)],
  55: [U("Digit 7 / stacked units", 15)],
  56: [U("Digit 8 / stacked units", 15)],
  57: [U("Digit 9 / stacked units", 15)],
  58: [T("Moss / shrub patch", 2), U("Colon (text)", 7)],
  59: [T("Mud / swamp debris", 6), U("Semicolon (text)", 7)],
  60: [U("Less-than (text)", 7), T("Up/down stair edge (some tilesets)", 14)],
  61: [I("Wood log", 6), I("Metal bar", 7), I("Block (stone / wood)", 7), B("Bridge segment", 6)],
  62: [U("Greater-than (text)", 7), T("Up/down stair edge (some tilesets)", 14)],
  63: [U("Unknown / unrevealed item", 15), I("Scroll / book (variant)", 6)],
  64: [C("Adventurer (player)", 15), C("Companion (adventure mode)", 11)],
  65: [U("Letter A (text)", 15)],
  66: [C("Birds (eagle, raven, turkey, peacock)", 15)],
  67: [C("Cow / livestock", 6), C("Colossus (bronze)", 6)],
  68: [C("Dragon", 12)],
  69: [C("Elephant", 8)],
  71: [C("Giants (cyclops, ettin)", 6)],
  79: [C("Ogre", 6)],
  83: [C("Giant spiders", 8)],
  84: [C("Troll", 6)],
  88: [U("X marker (cancel/blocked)", 12), T("Marked tile (digging)", 14)],
  90: [U("Letter Z / Z-level marker", 15)],
  91: [U("Open bracket (text)", 7), B("Archery target / stand (variant)", 6)],
  92: [U("Backslash (text)", 7), B("Lever (variant)", 7)],
  93: [U("Close bracket (text)", 7), B("Archery target / stand (variant)", 6)],
  94: [B("Trap (spikes / weapon)", 12), B("Raised drawbridge", 6), I("Scepter (variant)", 6)],
  95: [U("Underscore (text)", 7), T("Open pit / hatch below", 6)],
  96: [T("Dirt / ground debris", 6), U("Backtick (text)", 7)],
  97: [U("Letter a (text)", 15)],
  98: [C("Bat", 6), C("Giant bat", 6)],
  99: [C("Cat", 6)],
  100: [C("Dog", 6), C("War dog", 6), C("Jackal", 6)],
  102: [C("Fish", 9), C("Fox", 6)],
  103: [C("Goblin", 2), C("Gorlak", 6)],
  104: [C("Horse", 6)],
  105: [C("Fire imp", 12)],
  107: [C("Kobold", 6)],
  108: [C("Lizard", 2)],
  109: [C("Monkey", 6), C("Mule", 6)],
  112: [C("Pig", 12)],
  114: [C("Rat", 8), C("Rabbit", 15)],
  115: [C("Snake", 2), C("Sheep", 15)],
  116: [C("Tiger", 14), C("Toad", 2), C("Tortoise", 2)],
  119: [C("Wolf", 8), C("Worm", 6)],
  123:[U("Open brace (text)", 7), B("Archery target (variant)", 6)],
  124:[U("Vertical bar (text)", 7), B("Wall (thin)", 7), I("Weapon rack (variant)", 6)],
  125:[U("Close brace (text)", 7), B("Archery target (variant)", 6)],
  126:[T("Waves / river flow", 9), T("Magma flow (alt)", 12)],
  127:[B("Coffin", 7), B("Tomb / burial slab", 7), T("Open door / stairway", 6)],
  128:[U("Latin capital C with cedilla (name text)", 7)],
  129:[U("Latin u with diaeresis (name text)", 7)],
  145:[B("Chest", 6), U("Latin ae ligature (name text)", 7)],
  146:[B("Weapon rack", 6), U("Latin AE ligature (name text)", 7)],
  176:[T("Light shade: fog / mist", 7), T("Floor (rough / light shade)", 8), T("Smoke / steam (light)", 7)],
  177:[T("Medium shade: miasma", 13), T("Floor (medium shade)", 8), T("Smoke (medium)", 8)],
  178:[T("Dark shade: dense smoke / ash", 8), T("Fire (dark shade)", 12), T("Cave-in rubble", 7)],
  186:[T("Smoothed wall (double vertical)", 7), B("Fortress wall", 7)],
  205:[T("Smoothed wall (double horizontal)", 7), B("Fortress wall", 7)],
  206:[B("Fortification (cross)", 7), T("Smoothed wall (four-way)", 7)],
  219:[T("Wall (constructed block)", 7), T("Solid / fully obstructed tile", 8), I("Block (stone, wood)", 7)],
  220:[T("Lower half block (partial wall)", 7)],
  221:[T("Left half block (partial wall)", 7)],
  222:[T("Right half block (partial wall)", 7)],
  223:[T("Upper half block (partial wall)", 7)],
  227:[B("Table", 6), I("Pi (alt table)", 6)],
  232:[B("Table", 6), B("Throne dais", 14), U("Phi (text)", 7)],
  234:[B("Bed", 6), B("Barracks bed", 6), B("Tomb slot", 7)],
  240:[I("Bars (bundle)", 7), B("Grate (alt)", 7), I("Wooden planks", 6)],
  241:[T("Road (paved)", 7), T("Rough floor (stone)", 8), U("Plus/minus (text)", 7)],
  247:[T("Water (flowing)", 9), T("Magma", 12), T("River / brook", 9), T("Sea / ocean (world map)", 1)],
  248:[I("Ring (small)", 14), T("Bubbles / droplets", 11), U("Degree sign", 7)],
  249:[T("Floor / dirt", 6), T("Pebble", 8)],
  250:[T("Floor (smoothed)", 7), T("Grass (alt)", 10), T("Dirt road", 6)],
  251:[U("Root / check mark", 10), P("Wheat / crop sprout", 14)],
  254:[I("Stone block", 7), B("Floodgate / hatch", 7), B("Bridge (retracted)", 6), T("Raised floor", 7)],
};

// Auto-fill box-drawing glyphs (single / double / mixed lines).
for (let c = 179; c <= 218; c++) {
  if (!window.DF_ENTITIES[c]) {
    window.DF_ENTITIES[c] = [T("Smoothed stone wall segment", 7, "connects to neighbours"), B("Constructed wall segment", 7), B("Door / floodgate frame", 6)];
  }
}
